version: '3.7'

services:
    mongo:
        image: mongo:5.0.6
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: amphi
        ports:
            - 27017:27017
        volumes:
            - $HOME/Documents/Docker/mongodb:/data/db
            - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    