version: '3.8'

services:
    postgres:
        image: postgres
        container_name: amphi_postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: docker
        ports:
            - 5432:5432
        volumes:
            - $HOME/Documents/Docker/postgres:/var/lib/postgresql/data

    splash:
        image: scrapinghub/splash
        container_name: amphi_splash
        restart: always
        ports:
            - 8050:8050


    